### PR TITLE
Portfolio mobile menu

### PR DESCRIPTION
**Pull request by mbatha-17**
Created hamburger menu

### CODE REVIEW

**Comment by Becky449** [comment]
Hi @mbatha-17 
The hamburger is working on mobile view but not when you resize the window. But you can proceed to add the other code. Just use this branch don't change it.

**Comment by mbatha-17** [comment]
okay

**Comment by mbatha-17** [comment]
https://github.com/mbatha-17/portfolio/commit/66d9ef757c9737d0298b3e3266622e78fafd11ed

**Comment by mbatha-17** [comment]
https://github.com/mbatha-17/portfolio/commit/3e4932d590317a7baffd6ffd79022c43c61a6aa7

**Comment by mbatha-17** [comment]
https://github.com/mbatha-17/portfolio/commit/7e089e653cd410eb0f202c3e2e08adf0e2e86c9e

**Pull request merged**
