### PR TITLE
Created my first project

### PR DESCRIPTION
**Pull request by mbatha-17**
Created html and CSS files

### CODE REVIEW

**Comment by Becky449** [comment]
Hi @mbatha-17 
Kindly describe what the project is about

**Comment by Becky449** [comment]
Hi @mbatha-17 
While you have done a nice job on the code execution, You need to create the website according to the design. Follow the Figma design provided.

**Comment by mbatha-17** [comment]
> Hi @mbatha-17 Kindly describe what the project is about

Okay

**Comment by mbatha-17** [comment]
changed css layout

**Comment by mbatha-17** [comment]
changed css layout

**Pull request merged**
